name: hw-json
version: '0.9.0.0'
synopsis: Memory efficient JSON parser
description: Memory efficient JSON parser. Please see README.md
category: Data
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016 John Ky
license: BSD3
github: haskell-works/hw-json
homepage: http://github.com/haskell-works/hw-json#readme

extra-source-files:
- README.md
- corpus/5000B.bp
- corpus/5000B.ib
- corpus/5000B.json
- corpus/issue-0001.bp
- corpus/issue-0001.ib
- corpus/issue-0001.json
- corpus/issue-0001.md

ghc-options: -Wall

dependencies:
- base                >= 4          && < 5
- bytestring          >= 0.10.8     && < 0.11
- hw-balancedparens   >= 0.2.0.1    && < 0.3
- hw-bits             >= 0.7.0.2    && < 0.8
- hw-prim             >= 0.6.2.0    && < 0.7
- hw-rankselect       >= 0.10       && < 0.13
- hw-rankselect-base  >= 0.3        && < 0.4
- mmap                >= 0.5        && < 0.6
- vector              >= 0.12       && < 0.13

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -msse4.2
  dependencies:
  - array             >= 0.5        && < 0.6
  - ansi-wl-pprint    >= 0.6.8.2    && < 0.7
  - attoparsec        >= 0.13       && < 0.14
  - containers        >= 0.5        && < 0.7
  - dlist             >= 0.8        && < 0.9
  - hw-mquery         >= 0.1        && < 0.2
  - hw-parser         >= 0.1        && < 0.2
  - text              >= 1.2        && < 1.3
  - word8             >= 0.1        && < 0.2

executables:
  hw-json:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -msse4.2
    dependencies:
    - criterion             >= 1.4        && < 1.6
    - dlist                 >= 0.8        && < 0.9
    - hw-json
    - hw-mquery             >= 0.1        && < 0.2
    - generic-lens          >= 1          && < 1.1
    - lens                  >= 4          && < 5
    - optparse-applicative  >= 0.14       && < 0.15
    - resourcet             >= 1.2        && < 1.3

tests:
  hw-json-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - attoparsec        >= 0.13       && < 0.14
    - containers        >= 0.5        && < 0.7
    - hspec             >= 2.5        && < 2.6
    - hw-json
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover

benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -O2
    - -msse4.2
    dependencies:
    - criterion         >= 1.4        && < 1.6
    - directory         >= 1.3        && < 1.4
    - hw-json

when:
- condition: (flag(sse42))
  ghc-options:
  - -mbmi2
- condition: (flag(bmi2)) && (impl(ghc >=8.4.1))
  ghc-options:
  - -mbmi2
  - -msse4.2
  cpp-options:
  - -DBMI2_ENABLED

flags:
  sse42:
    description: Enable sse4.2 instruction set
    manual: false
    default: false
  bmi2:
    description: Enable bmi2 instruction set
    manual: false
    default: false
