name: hw-json
version: '0.7.0.1'
synopsis: Memory efficient JSON parser
description: Memory efficient JSON parser. Please see README.md
category: Data
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016 John Ky
license: BSD3
github: haskell-works/hw-json
homepage: http://github.com/haskell-works/hw-json#readme
extra-source-files:
- README.md
- corpus/5000B.bp
- corpus/5000B.ib
- corpus/5000B.json
- corpus/issue-0001.bp
- corpus/issue-0001.ib
- corpus/issue-0001.json
- corpus/issue-0001.md
ghc-options: -Wall
dependencies:
- base >=4 && <5
- bytestring
- hw-balancedparens >=0.1.0.0
- hw-bits >=0.4.0.0
- hw-prim >=0.4.0.0
- hw-rankselect >=0.8.0.0
- hw-rankselect-base >=0.2.0.0
- mmap
- resourcet
- vector
library:
  source-dirs: src
  ghc-options:
  - -O2
  - -msse4.2
  dependencies:
  - array
  - ansi-wl-pprint
  - attoparsec
  - containers
  - dlist
  - hw-mquery >=0.1.0.0
  - hw-parser >=0.0.0.1
  - mono-traversable
  - text
  - word8
executables:
  hw-json-example:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -msse4.2
    dependencies:
    - array
    - ansi-wl-pprint
    - attoparsec
    - containers
    - criterion
    - dlist
    - hw-diagnostics >=0.0.0.5
    - hw-json
    - hw-mquery >=0.1.0.0
    - hw-parser >=0.0.0.1
    - mono-traversable
    - text
    - word8
tests:
  hw-json-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - attoparsec
    - containers
    - hspec
    - hw-json
    - parsec
    - QuickCheck
    - transformers
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover
benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -O2
    - -msse4.2
    dependencies:
    - criterion
    - hw-json

when:
- condition: (flag(sse42))
  ghc-options:
  - -mbmi2
- condition: (flag(bmi2)) && (impl(ghc >=8.4.1))
  ghc-options:
  - -mbmi2
  - -msse4.2
  cpp-options:
  - -DBMI2_ENABLED

flags:
  sse42:
    description: Enable sse4.2 instruction set
    manual: false
    default: false
  bmi2:
    description: Enable bmi2 instruction set
    manual: false
    default: false
